name: Deploy Based on Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - prod
      

jobs:
  # Job for Staging Environment Deployment
  staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'staging' }}
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"

  # Job for Production Environment Deployment
  prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"
